[versions]
agp = "8.9.2"
kotlin = "2.1.20"
junit = "4.13.2"
androidx-junit = "1.2.1"
androidx-runner = "1.6.2"
json = "20240303"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-runner = { module = "androidx.test:runner", version.ref = "androidx-runner" }
json-test = { module = "org.json:json", version.ref = "json" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
